version: '3.8'
services:
  legacy_postgres:
    restart: always
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: legacy_movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"