spring:
  datasource:
    #url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost/movies}
    url: jdbc:mysql://localhost/movies
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui
server:
  port: ${PORT:8080}

jwt:
  secret: very_long_text
  validity: 43200