#Settigns spring's
spring:
  datasource:
    url: jdbc:mysql://localhost/movies
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui

#Settigns servers
server:
  port: 8080

#Settings JWT
jwt:
  secret: very_long_text
  validity: 43200000

#Settings Actuator
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
