#Settigns spring's
spring:
  datasource:
    url: jdbc:mysql://localhost/movies
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

#Settigns servers
server:
  port: 433
  ssl:
    key-store: classpath:movies.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: movies
    key-password: password
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

#Settings JWT
jwt:
  secret: very_long_text
  validity: 43200000

#Settings Actuator
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
