#Settigns spring's
spring:
  datasource:
    url: jdbc:postgresql://dpg-cghvs5g2qv2772gan2j0-a.frankfurt-postgres.render.com/movies_jhmn
    username: user
    password: xGkhZtjVoVkTEdxTze5YNLIjKrPtj7mC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Settigns servers
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

#Settings JWT
jwt:
  secret: very_long_text
  validity: 43200000

#Settings Actuator
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
