spring:
  datasource:
    url: jdbc:mysql://localhost/movies
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui