#Settigns spring's
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost/movies}
    username: ${USERNAME:postgres}
    password: ${PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#Settigns servers
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui

#Settings JWT
jwt:
  secret: very_long_text
  validity: 43200000

#Settings Actuator
management:
  endpoints:
    web:
      base-path: /
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
